hl.on("hyprland.start", function()
    hl.exec_cmd("kbuildsycoca6")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("/usr/lib/mate-polkit/polkit-mate-authentication-agent-1")
    hl.exec_cmd("~/.config/hypr/scripts/display-startup.sh")
    hl.exec_cmd("sunshine")
    hl.exec_cmd("~/.config/hypr/scripts/startup.sh")
end)
