cursor #e7e2d5
cursor_text_color #cbc7b5

foreground            #e7e2d5
background            #14140c
selection_foreground  #333117
selection_background  #cdc8a3
url_color             #d1c973

color0   #14140c
color1   #f07a6c
color2   #75d168
color3   #ffe872
color4   #c6bd5b
color5   #605910
color6   #d1c973
color7   #dbdace
color8   #87867d
color9   #ffa99f
color10  #aefaa3
color11  #fff0a5
color12  #e5de8e
color13  #fff8ae
color14  #fffacb
color15  #fffef8
