cursor #e5e1e3
cursor_text_color #c9c5c7

foreground            #e5e1e3
background            #141315
selection_foreground  #312f38
selection_background  #c9c5d0
url_color             #c9c4d6

color0   #141315
color1   #f66e8a
color2   #6bd681
color3   #ffda72
color4   #bcb6cb
color5   #585363
color6   #c9c4d6
color7   #d7d3e0
color8   #83808b
color9   #ff9fb3
color10  #a5ffb8
color11  #ffe7a5
color12  #dfdaeb
color13  #f4efff
color14  #f8f5ff
color15  #faf8ff
